# sets maximal velocity and acceleration values along the trajectory
dynamic_params: {
  max_v: 5.0,
  max_a: 2.0
}

waypoints: {
  # your waypoints here. Think about how to best add any number of waypoints
  # and the according velocity and acceleration constraints.
  x: [10.0, 30.0, 35.0, 35.0, 30.0, 27.0, 24.0, 23.0, 21.0, 20.0, 18.0, 16.0, 14.0],
  y: [0.0, 10.0, 25.0, 35.0, 39.0, 39.0, 39.0, 39.0, 39.0, 39.0, 39.0, 39.0, 39.0],
  z: [3.0, 3.0, 13.0, 6.0, 11.0, 11.0, 11.0, 11.0, 11.0, 11.0, 11.0, 11.0, 11.0]
}
